name: brother_admin_panel
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  clipboard: ^0.1.3

  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  data_table_2: ^2.5.18
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  firebase_storage: ^12.4.7
  path_provider: ^2.1.1
  cloud_firestore: ^5.6.0
  js: ^0.6.7
  flutter_staggered_grid_view: ^0.7.0

  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_native_splash: ^2.3.7
  flutter_typeahead:
  get: ^4.6.5
  get_storage: ^2.1.1
  iconsax:
  image_picker: ^1.0.7
  image_cropper: ^8.0.2
  # image_cropper_for_web: ^3.0.0  # يسبب أخطاء على Flutter Web
  uuid: ^4.3.3
  intl: ^0.19.0
  lottie: ^2.6.0
  multi_select_flutter: any
  shimmer: ^3.0.0
  url_launcher: ^6.1.14
  http: ^1.1.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Desktop Window Management
  window_manager: ^0.3.7
  desktop_window: ^0.4.0
  msix: ^3.16.12

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

    #assets\images\users\img.png
    - assets/images/users/
    #- assets/images/contents
    - assets/icons/
    - assets/fonts/
    - assets/images/logos/
    - assets/images/lottie/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/Urbanist-Thin.ttf
          weight: 100
        - asset: assets/fonts/Urbanist/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Urbanist/Urbanist-Black.ttf
          weight: 900
